name: Fetch News Headlines

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  fetch-headlines:
    runs-on: ubuntu-latest
    
    permissions:
      # Important: give the workflow permission to push changes
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script needs
    
    - name: Run headline fetching script
      run: python fetch-news.py

    
    - name: Commit and push changes
      env:
        # Use the built-in GitHub token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add headlines.txt
        git commit -m "Update headlines $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
