name: Post image to tumblr

on:
  schedule:
    # Run every 24 hours
    - cron: '0 18 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  post-to-tumblr:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
  
    permissions:
      # Important: give the workflow permission to push changes
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytumblr
        pip install python-dotenv

    - name: create .env file
      run: |
        touch .env
        echo API_KEY: ${{ secrets.API_KEY }} >> .env
        echo SECRET_KEY: ${{ secrets.SECRET_KEY }} >> .env
        echo OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }} >> .env
        echo OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }} >> .env
    
    - name: Run posting script
      run: python tumblr_post.py

    
    - name: Commit and push changes
      env:
        # Use the built-in GitHub token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "posted image $(date +'%Y-%m-%d')" || exit 0
        git push
